name: bloc_test
description: >
  A testing library which makes it easy to test blocs. Built to be used with the bloc state management package.
version: 0.0.0-develop
repository: https://github.com/PlugFox/bloc/tree/master/packages/bloc_test
issue_tracker: https://github.com/PlugFox/bloc/issues
homepage: https://github.com/PlugFox/bloc
#documentation: https://bloclibrary.dev/#/gettingstarted

publish_to: none

environment:
  sdk: ^2.13.0

dependencies:
  bloc:
    git:
      url: 'https://github.com/PlugFox/bloc.git'
      ref: 'develop'
      path: 'packages/bloc'
  meta: ^1.3.0
  mocktail: ^0.1.1
  test: ^1.16.0

dev_dependencies:
  pedantic: ^1.10.0
  rxdart: ^0.26.0
