name: fox_flutter_bloc_example
description: Flutter BLoC example
version: 0.1.0-develop

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fox_flutter_bloc:
    path: ../

dependency_overrides:
  fox_flutter_bloc:
    path: ../

dev_dependencies:
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
