name: flutter_bloc
description: >
  Flutter Widgets that make it easy to implement the BLoC (Business Logic Component) design pattern.
  Built to be used with the bloc state management package.
version: 8.0.0-develop
repository: https://github.com/PlugFox/bloc/tree/master/packages/flutter_bloc
issue_tracker: https://github.com/PlugFox/bloc/issues
homepage: https://github.com/PlugFox/bloc
#documentation: https://bloclibrary.dev/#/gettingstarted

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc:
    git:
      url: 'https://github.com/PlugFox/bloc.git'
      ref: 'develop'
      path: 'packages/bloc'
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
