name: flutter_bloc
description: >
  Flutter Widgets that make it easy to implement the BLoC (Business Logic Component) design pattern.
  Built to be used with the bloc state management package.
version: 0.0.0-develop
repository: https://github.com/PlugFox/bloc/tree/master/packages/flutter_bloc
issue_tracker: https://github.com/PlugFox/bloc/issues
homepage: https://github.com/PlugFox/bloc
#documentation: https://bloclibrary.dev/#/gettingstarted

publish_to: none

environment:
  sdk: ^2.13.0
  flutter: ^2.2.0

dependencies:
  flutter:
    sdk: flutter

  bloc:
    git:
      url: 'https://github.com/PlugFox/bloc.git'
      ref: 'develop'
      path: 'packages/bloc'

  flutter_scope:
    git:
      url: 'https://github.com/PlugFox/bloc.git'
      ref: 'develop'
      path: 'packages/flutter_scope'

dev_dependencies:
  flutter_test:
    sdk: flutter
