name: fox_flutter_bloc
description: >
  Flutter Widgets that make it easy to implement the BLoC (Business Logic Component) design pattern.
  Built to be used with the bloc state management package.
version: 0.1.0
repository: https://github.com/PlugFox/bloc/tree/master/packages/flutter_bloc
issue_tracker: https://github.com/PlugFox/bloc/issues
homepage: https://github.com/PlugFox/bloc
#documentation: https://bloclibrary.dev/#/gettingstarted

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  fox_core_bloc: ^0.1.0

  fox_flutter_scope: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
