name: fox_flutter_scope_examples
description: fox_flutter_scope_examples

version: 0.1.0+1-develop

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fox_flutter_scope: ^0.1.0-develop

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
