name: fox_flutter_scope
description: >
  A wrapper around InheritedWidget to make them easier to use and more reusable.
version: 0.1.0-develop
repository: https://github.com/PlugFox/bloc/tree/master/packages/flutter_scope
issue_tracker: https://github.com/PlugFox/bloc/issues
homepage: https://github.com/PlugFox/bloc
#documentation: https://bloclibrary.dev/#/gettingstarted

environment:
  sdk: ^2.13.0
  flutter: ^2.2.0

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  fox_core_scope: ^0.1.0-develop

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
