name: core_scope
description: >
  A wrapper around InheritedWidget to make them easier to use and more reusable.
version: 0.0.0-develop
repository: https://github.com/PlugFox/bloc/tree/master/packages/core_scope
issue_tracker: https://github.com/PlugFox/bloc/issues
homepage: https://github.com/PlugFox/bloc
#documentation: https://bloclibrary.dev/#/gettingstarted

publish_to: none

environment:
  sdk: ^2.13.0

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0

dev_dependencies:
  lints: ^1.0.1
